packaging: bin: die as expected if java home is not found
export always return success, so set in two phases.

Change-Id: I2546c30f7e104a7538e0f7b267830f730d35c8d3
Signed-off-by: Alon Bar-Lev <alonbl@redhat.com>

diff --git a/packaging/bin/engine-prolog.sh.in b/packaging/bin/engine-prolog.sh.in
--- a/packaging/bin/engine-prolog.sh.in
+++ b/packaging/bin/engine-prolog.sh.in
@@ -24,7 +24,8 @@ load_config() {
 		[ -r "${f}" ] && . "${f}"
 	done
 
-	export JAVA_HOME="$("${ENGINE_USR}/bin/java-home")" || die "Cannot set JAVA_HOME"
+	JAVA_HOME="$("${ENGINE_USR}/bin/java-home")" || die "Cannot set JAVA_HOME"
+	export JAVA_HOME
 
 	# we use jboss specific loader (jboss-modules.jar)
 	# setup module path
