packaging: detect java home at runtime
CURRENT IMPLEMENTATION

detect java home during installation.

advantage is optimize application execution post-setup.

disadvantage is that java home may be altered by system updates.

NEW IMPLEMENTATION

detect java home during runtime using pre-defined algorithm.

algorithm:

execute /usr/share/ovirt-engine/bin/java-home.

if java-home.local is available, execute that script. this enables
distro specific customization.

if OVIRT_ENGINE_JAVA_HOME environment is set, validate java validity
and use/abort.

search predefined selected alternatives location by order, first wins.

search /usr/lib/jvm for compatible jvm.

NOTES

the java-home script resides with the lib package as it cannot reside
within any version locked package since it is used by setup, and it
cannot reside within setup since it used by post setup.

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1009863
Change-Id: I833362d0498d534b06e0d7660f1e8a61e9b1713b
Signed-off-by: Alon Bar-Lev <alonbl@redhat.com>

diff --git a/packaging/bin/engine-prolog.sh.in b/packaging/bin/engine-prolog.sh.in
--- a/packaging/bin/engine-prolog.sh.in
+++ b/packaging/bin/engine-prolog.sh.in
@@ -24,6 +24,8 @@ load_config() {
 		[ -r "${f}" ] && . "${f}"
 	done
 
+	export JAVA_HOME="$("${ENGINE_USR}/bin/java-home")" || die "Cannot set JAVA_HOME"
+
 	# we use jboss specific loader (jboss-modules.jar)
 	# setup module path
 	export JAVA_MODULEPATH="${ENGINE_USR}/modules:${JBOSS_HOME}/modules"
