packaging: use conf.d notation in shell utilities
Change-Id: Icb03986e385cf786fa191095ad7fcc443d2f1199
Signed-off-by: Alon Bar-Lev <alonbl@redhat.com>

diff --git a/backend/manager/tools/src/main/shell/engine-prolog.sh.in b/backend/manager/tools/src/main/shell/engine-prolog.sh.in
--- a/backend/manager/tools/src/main/shell/engine-prolog.sh.in
+++ b/backend/manager/tools/src/main/shell/engine-prolog.sh.in
@@ -8,20 +8,20 @@ load_config() {
     # Load the defaults file:
     ENGINE_DEFAULTS="${ENGINE_DEFAULTS:-@ENGINE_DEFAULTS@}"
     export ENGINE_DEFAULTS
-    if [ ! -r "${ENGINE_DEFAULTS}" ]
-    then
-        die "Can't load defaults file \"${ENGINE_DEFAULTS}\"."
-    fi
-    . "${ENGINE_DEFAULTS}"
 
     # Load the configuration file:
     ENGINE_VARS="${ENGINE_VARS:-@ENGINE_VARS@}"
     export ENGINE_VARS
-    if [ ! -r "${ENGINE_VARS}" ]
-    then
-        die "Can't load configuration file \"${ENGINE_VARS}\"."
-    fi
-    . "${ENGINE_VARS}"
+
+    [ -r "${ENGINE_DEFAULTS}" ] || die "Can't load defaults file \"${ENGINE_DEFAULTS}\"."
+
+    for f in \
+            "${ENGINE_DEFAULTS}" \
+            "${ENGINE_VARS}" \
+            $([ -d "${ENGINE_VARS}.d" ] && find "${ENGINE_VARS}.d" -name '*.conf' | sort) \
+            ; do
+        [ -r "${f}" ] && . "${f}"
+    done
 
     # Clean the class path:
     CLASSPATH=""
