packaging: setup: Check health
This patch introduces a new utility that can create a standalone script
that can be copied to an older engine machine and ran to get a report.

Currently this report does not do much, but it's expected that we'll
move most of the checks done during engine-setup to be ran also by this
script.

Details:

packaging/setup/bin/bundle-ovirt-engine-health

- creates this "bundle" standalone script

packaging/setup/bin/ovirt-engine-health

- The health checker itself. Can also be ran directly on the engine
  machine, but is mainly intended to be wrapped in the bundle.

packaging/setup/plugins/ovirt-engine-checks:

- A new plugins directory, that is shared by both engine-setup and
ovirt-engine-health.

packaging/setup/plugins/ovirt-engine-health:

- A new plugins directory, specific to the health checker

Also patched the spec and make files to allow building.

Also added packaging/setup/plugins/README to document this directory a
bit.

Also copied the code that checks cluster/DC versions compatibility to a
new plugin in plugins/ovirt-engine-checks, as a POC.

To try this, on the engine machine, after setup, run:

sh /usr/share/ovirt-engine/setup/bin/bundle-ovirt-engine-health

It will create (by default) ovirt-engine-health-check.run in current
directory. Copy this one to the target machine and run it there.

Change-Id: Iafb49d107c3b2b5623d11d0c4bbf907d6398e987
Signed-off-by: Yedidyah Bar David <didi@redhat.com>

diff --git a/packaging/setup/bin/ovirt-engine-health b/packaging/setup/bin/ovirt-engine-health
--- a/packaging/setup/bin/ovirt-engine-health
+++ b/packaging/setup/bin/ovirt-engine-health
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
-# ovirt-engine-setup -- ovirt engine setup
-# Copyright (C) 2013 Red Hat, Inc.
+# ovirt-engine-health -- ovirt engine setup health check
+# Copyright (C) 2017 Red Hat, Inc.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -25,8 +25,8 @@ Usage: $0
         Load configuration files.
     --config-append=file
         Load extra configuration files or answer file.
-    --offline
-        Offline mode.
+    --no-offline
+        Online mode.
     --generate-answer=file
         Generate answer file.
     --reconfigure-optional-components
@@ -45,9 +45,11 @@ __EOF__
 script="$(readlink -f "$0")"
 scriptdir="$(dirname "${script}")"
 . "${scriptdir}/ovirt-engine-setup.env"
-baseenv="\"APPEND:BASE/pluginPath=str:${scriptdir}/../plugins\" APPEND:BASE/pluginGroups=str:ovirt-engine-common:ovirt-engine-setup:ovirt-engine-checks"
+baseenv="\"APPEND:BASE/pluginPath=str:${scriptdir}/../plugins\" APPEND:BASE/pluginGroups=str:ovirt-engine-common:ovirt-engine-checks:ovirt-engine-health"
 otopienv=""
 environment=""
+
+OFFLINE=1
 
 while [ -n "$1" ]; do
 	x="$1"
@@ -72,8 +74,8 @@ while [ -n "$1" ]; do
 		--jboss-home=*)
 			environment="${environment} \"OVESETUP_CONFIG/jbossHome=str:${v}\""
 		;;
-		--offline)
-			environment="${environment} OVESETUP_CORE/offlinePackager=bool:True PACKAGER/yumpackagerEnabled=bool:False"
+		--no-offline)
+			OFFLINE=
 		;;
 		--reconfigure-optional-components)
 			environment="${environment} OVESETUP_CORE/reconfigureOptionalComponents=bool:True"
@@ -92,5 +94,12 @@ while [ -n "$1" ]; do
 		;;
 	esac
 done
+
+[ -n "${OFFLINE}" ] && environment="${environment} OVESETUP_CORE/offlinePackager=bool:True PACKAGER/yumpackagerEnabled=bool:False"
+
+if ! python -c 'import psycopg2' > /dev/null 2>&1; then
+	echo "Missing library psycopg2. This is probably not an oVirt engine machine."
+	exit 1
+fi
 
 exec "${otopidir}/otopi" "${baseenv} ${environment} ${otopienv}"
