build: Output isort --diff
To ease seeing what changes are needed.

Change-Id: I60c351452bdeac812b569ad6708d5a860e449426
Signed-off-by: Yedidyah Bar David <didi@redhat.com>

diff --git a/build/python-check.sh.in b/build/python-check.sh.in
--- a/build/python-check.sh.in
+++ b/build/python-check.sh.in
@@ -23,9 +23,11 @@ for exe in "${PYFLAKES}" "${PEP8}"; do
 done
 
 if ! which "${ISORT}" > /dev/null 2>&1; then
-    echo "WARNING: tool '${ISORT}' is missing" >&2
+	echo "WARNING: tool '${ISORT}' is missing" >&2
 else
-    "${ISORT}" --check ${FILES} || ret=1
+	"${ISORT}" --check ${FILES} || ret=1
+	echo isort --diff:
+	"${ISORT}" --diff ${FILES}
 fi
 
 exit ${ret}
