packaging: build: optionally use pep8 and pyflakes
Change-Id: I4d8f6b009f6c5bf1ccd7b1cde48d8474e5e47340
Signed-off-by: Alon Bar-Lev <alonbl@redhat.com>

diff --git a/build/python-check.sh.in b/build/python-check.sh.in
--- a/build/python-check.sh.in
+++ b/build/python-check.sh.in
@@ -13,7 +13,11 @@ FILES="$(
 	done
 )"
 
-"${PYFLAKES}" ${FILES} || ret=1
-"${PEP8}" ${FILES} || ret=1
-
+for exe in "${PYFLAKES}" "${PEP8}"; do
+	if ! which "${exe}" > /dev/null 2>&1; then
+		echo "WARNING: tool '${exe}' is missing" >&2
+	else
+		"${exe}" ${FILES} || ret=1
+	fi
+done
 exit ${ret}
